spring:
  main:
    web-application-type: none
  application:
    ui:
      title: Spring FX client
  datasource:
    url: jdbc:h2:file:./db/client/demodb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
